name: probatioed
title: probatioed
version: '1.8.0'
summary: The daemon behind probatio
description: |
  This daemon is responsible for the distribution and the use of data for probatio...

grade: stable
confinement: strict
base: core18

website: https://github.com/BenCoepp/probatio
issues: https://github.com/BenCoepp/probatio/issues
license: MIT

architectures:
  - build-on: amd64

apps:
  probatio:
    command:
      java -jar -Duser.home=$SNAP_USER_DATA $SNAP/jar/daemon-0.0.1-SNAPSHOT
    plugs: [ home, network]
    daemon: simple

parts:
  probatio:
    source: https://github.com/BenCoepp/probatio.git
    source-tag: main
    source-type: git
    source-subdir: daemon
    plugin: maven
    stage:
      - -usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs
      - -etc/java-11-openjdk/security/blacklisted.certs lint-snap-v2_external_symlinks
  java:
    plugin: autotools
    source: https://download.oracle.com/java/19/latest/jdk-19_linux-x64_bin.deb
    override-build: |
      echo "Build Java"
      apt-get install ca-certificates-java ca-certificates -y
      update-alternatives --install /usr/bin/java java /build/probatio/parts/java/build/usr/lib/jvm/jdk-19/bin/java 1919